language: minimal

deploy:
  - provider: cloudformation
    edge: true
    access_key_id: AKIAYHGAO4YHNE6XBI4U
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-1
    template: application.cfn.yaml
    stack_name: ipv8-website
    capabilities: CAPABILITY_NAMED_IAM
  - provider: s3
    access_key_id: AKIAYHGAO4YHNE6XBI4U
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-1
    bucket: ipv8-website
    local-dir: html
    acl: private
    on:
      repo: jonathanjuursema/ipv8.net